#!/bin/sh

MESSAGE=$1

read -r MSG_CONTENT < "$MESSAGE"

REGEX="^#([0-9]+) - .+"

if ! [[  "$MSG_CONTENT" =~ $REGEX ]]; then
        echo "Padrão inválido! Você deve seguir o padrão #NUM_ISSUE - MENSAGEM"
        exit 1
else
        issue="${BASH_REMATCH[1]}"
        RESPONSE=$(curl -s -L -i \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer <YOUR_TOKEN>" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/ianbarreto22/SistemaBancario/issues/$issue | grep -w "state" | awk -F: '{print $2}' | tr -d '," ')

	if [[ -z "$RESPONSE" ]]; then   
		echo "Issue não encontrada! #NUM_ISSUE deve existir no repositório"
		exit 1
	fi
	
	OPEN="open"
	if ! [[ "$RESPONSE" =~ $OPEN ]]; then
		echo "Esta issue já foi fechada! A #NUM_ISSUE deve estar aberta"
		exit 1
	fi
fi



