name: Validação Main
run-name: Validação
on:
  push:
    branches:
      - 'main'
    
jobs:

  resolver-dependencias:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Resolvendo dependências...
        run: mvn clean install package
      
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurando JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build com Maven
        run: mvn -B package --file pom.xml
      - name: Docker Build
        run: docker build . --file Dockerfile --tag SistemaBancario:latest
      
  testes-unitarios:
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Realizando testes unitários...
        run: mvn test

  criar-tag:
    needs: [resolver-dependencias, build, testes-unitarios]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/chevkout@v3
      - name: Criando tag...
        run: |
             git config --local user.email "actions@github.com"
             git config --local user.name "GitHub Actions"
             export build_name=build-$(date +'%Y-%m-%d-%H-%M-%S')
             git tag $build_name
             git push origin $build_name
    
  
