name: release
run-name: release
on:
  push:
    tags:    
      - 'rel-[0-9]+\.[0-9]+'
      
jobs:

  resolver-dependencias:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Resolvendo dependências...
        run: mvn clean install package
        
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurando JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build com Maven
        run: mvn -B package --file pom.xml
        
  quality:
    runs-on: ubuntu-latest  
    steps:   
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Executar Checkstyle
        run: mvn checkstyle:checkstyle
    
  testes-unitarios:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
       - name: Set up JDK 17
         uses: actions/setup-java@v3
         with:
           java-version: '17'
           distribution: 'temurin'
           cache: maven
       - name: Realizando testes unitários...
         run: mvn test     
        
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Pacote Release
        uses: actions/upload-artifact@v3
        with: 
          name: release-result
          path: ./target/SistemaBancario-0.0.1-SNAPSHOT.jar
          
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Build
        run: docker build . --file Dockerfile --tag sistemabancario:latest
      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Push
        run: docker tag sistemabancario:latest ianbarreto/sistemabancario && docker push ianbarreto/sistemabancario
