name: staging-tag
run-name: staging-tag
on:
  push:
    tags:    
      - 'rc-[0-9]+\.[0-9]+'
      
jobs:

  resolver-dependencias:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Resolvendo dependências...
        run: mvn clean install package
        
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurando JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build com Maven
        run: mvn -B package --file pom.xml
      - name: Docker Build
        run: docker build . --file Dockerfile --tag sistemabancario:latest
        
  quality:
    runs-on: ubuntu-latest  
    steps:   
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Executar Snyk
        uses: snyk/actions/maven-3-jdk-17@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
    
  testes-unitarios:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
       - name: Set up JDK 17
         uses: actions/setup-java@v3
         with:
           java-version: '17'
           distribution: 'temurin'
           cache: maven
       - name: Realizando testes unitários...
         run: mvn test     
        
  staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Pacote Estabilizacao
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: '${{ github.base.ref }}.zip'
          exclusions: '*.git* .classpath'
      - name: Disponibilizar Pacote
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "rc.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
        
        
        
        
        
        
        
        
        
        
        
        
